# Generated by Django 3.1.2 on 2021-03-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('postcode', models.CharField(max_length=7, null=True)),
                ('first_line_address', models.CharField(max_length=200, null=True)),
                ('credit_class', models.IntegerField(null=True)),
                ('add_lines_available', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True)),
            ],
        ),
    ]
