# Generated by Django 3.1.2 on 2021-03-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=11, null=True)),
                ('number', models.CharField(max_length=11, null=True)),
                ('contract_type', models.CharField(choices=[('Handset', 'Handset'), ('Sim-Only', 'Sim-Only')], max_length=10, null=True)),
                ('plan', models.CharField(max_length=100, null=True)),
                ('mrc', models.FloatField(null=True)),
                ('device_manufacture', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung')], max_length=100, null=True)),
                ('device_model', models.CharField(max_length=100, null=True)),
                ('insurance', models.BooleanField(default=False, null=True)),
                ('data_allowance', models.FloatField(max_length=6, null=True)),
                ('spend_cap', models.CharField(choices=[('None', 'None'), ('0', '0'), ('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=100, null=True)),
                ('contract_start', models.DateField(null=True)),
                ('contract_end', models.DateField(null=True)),
                ('contract_length_months', models.CharField(choices=[('1', '1'), ('12', '12'), ('18', '18'), ('24', '24')], max_length=10, null=True)),
                ('friends_and_family', models.BooleanField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
