# Generated by Django 3.1.2 on 2021-03-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimOnlyTariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_length', models.CharField(choices=[('1', '1'), ('12', '12'), ('18', '18'), ('24', '24')], max_length=10, null=True)),
                ('mrc', models.FloatField(null=True)),
                ('upfront', models.FloatField(null=True)),
                ('data_allowance', models.CharField(choices=[('0.25', '0.25'), ('1', '1'), ('3', '3'), ('20', '20'), ('60', '60'), ('100', '100'), ('200', '200'), ('1000', '1000')], max_length=10, null=True)),
                ('plan_type', models.CharField(choices=[('Standard', 'Standard')], max_length=10, null=True)),
            ],
        ),
    ]
