# Generated by Django 3.1.2 on 2021-03-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210312_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlytariffs',
            name='tariff_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
