# Generated by Django 3.1.2 on 2021-03-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_simonlytariffs_tariff_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simonlyorder',
            options={'verbose_name_plural': 'Sim Only Orders'},
        ),
        migrations.AddField(
            model_name='simonlyorder',
            name='plan_type',
            field=models.CharField(choices=[('Standard', 'Standard')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='simonlyorder',
            name='contract_type',
            field=models.CharField(choices=[('Sim-Only', 'Sim-Only')], max_length=20, null=True),
        ),
    ]
