# Generated by Django 3.1.2 on 2021-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210317_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='excess_fee',
            field=models.CharField(blank=True, choices=[('120', '120'), ('100', '100')], max_length=200, null=True),
        ),
    ]
