# Generated by Django 3.1.2 on 2021-03-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210319_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='cap',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.spendcaps'),
        ),
        migrations.AlterField(
            model_name='spendcaps',
            name='cap_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
