# Generated by Django 3.1.2 on 2021-03-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210319_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='existing_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.insurance'),
        ),
        migrations.AlterField(
            model_name='simonlyorder',
            name='cap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.spendcaps'),
        ),
        migrations.AlterField(
            model_name='simonlyorder',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.simonlytariffs'),
        ),
    ]
