# Generated by Django 3.1.2 on 2021-03-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210320_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='simonlyorder',
            name='order_created_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simonlyorder',
            name='order_submitted_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
