# Generated by Django 3.1.2 on 2021-03-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_simonlyorder_friends_and_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handsets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung')], max_length=30, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('storage', models.IntegerField(null=True)),
                ('speed_type', models.CharField(choices=[('5G', '5G'), ('4G', '4G')], max_length=30, null=True)),
                ('colour', models.CharField(max_length=100, null=True)),
                ('cost_price', models.FloatField(max_length=10)),
                ('mrc', models.FloatField(null=True)),
                ('upfront', models.FloatField(null=True)),
                ('product_code', models.IntegerField(null=True)),
                ('insurance_available', models.ManyToManyField(to='api.Insurance')),
            ],
            options={
                'verbose_name_plural': 'Handsets',
                'ordering': ['manufacture', 'model'],
            },
        ),
    ]
