# Generated by Django 3.1.2 on 2021-03-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_handsets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handsets',
            name='product_code',
        ),
    ]
