# Generated by Django 3.1.2 on 2021-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_handsets_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandsetTariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_length', models.CharField(choices=[('24', '24')], max_length=10, null=True)),
                ('mrc', models.FloatField(null=True)),
                ('upfront', models.FloatField(null=True)),
                ('data_allowance', models.CharField(choices=[('0.25', '0.25'), ('1', '1'), ('4', '4'), ('10', '10'), ('40', '40'), ('100', '100'), ('1000', '1000')], max_length=10, null=True)),
                ('plan_type', models.CharField(choices=[('Standard', 'Standard')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Handset Tariffs',
            },
        ),
    ]
