# Generated by Django 3.1.2 on 2021-03-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_handsettariffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsets',
            name='tariffs_available',
            field=models.ManyToManyField(to='api.HandsetTariffs'),
        ),
    ]
