# Generated by Django 3.1.2 on 2021-03-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_handsets_tariffs_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsets',
            name='tariffs_available',
            field=models.ManyToManyField(blank=True, null=True, to='api.HandsetTariffs'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_content', models.CharField(blank=True, max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
