# Generated by Django 3.1.2 on 2021-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210401_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created_by',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
