# Generated by Django 3.1.2 on 2021-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_notes_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_last_accessed_by',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_last_accessed_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
