# Generated by Django 3.1.2 on 2021-04-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210401_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilenumber',
            name='account_last_accessed_date_time',
        ),
    ]
