# Generated by Django 3.1.2 on 2021-04-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_mobilenumber_account_last_accessed_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumber',
            name='account_last_accessed_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
