# Generated by Django 3.1.2 on 2021-04-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_mobilenumber_account_last_accessed_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandsetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctn', models.CharField(max_length=11, null=True)),
                ('contract_length', models.CharField(choices=[('24', '24')], max_length=2, null=True)),
                ('contract_type', models.CharField(choices=[('Handset', 'Handset')], max_length=30, null=True)),
                ('plan_type', models.CharField(choices=[('Standard', 'Standard')], max_length=30, null=True)),
                ('early_upgrade_fee', models.FloatField(default=0, null=True)),
                ('upfront', models.FloatField(default=0.0, null=True)),
                ('friends_and_family', models.BooleanField(default=False, null=True)),
                ('handset_credit', models.IntegerField(default=0, null=True)),
                ('one_hundred_day_promo', models.BooleanField(default=False, null=True)),
                ('cap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.spendcaps')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer')),
                ('handset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.handsets')),
                ('handset_tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.handsettariffs')),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.insurance')),
            ],
            options={
                'verbose_name_plural': 'Handset Orders',
            },
        ),
    ]
