# Generated by Django 3.1.2 on 2021-04-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210407_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsetorder',
            name='handset_imei',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='HandsetStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, null=True)),
                ('handset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.handsets')),
            ],
            options={
                'verbose_name_plural': 'Handset Stock',
            },
        ),
    ]
