# Generated by Django 3.1.2 on 2021-04-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210408_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='handsetstock',
            name='sold',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='handsetstock',
            name='sold_ctn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mobilenumber'),
        ),
        migrations.AlterField(
            model_name='handsetstock',
            name='imei',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
