# Generated by Django 3.1.2 on 2021-04-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210409_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_type',
            field=models.CharField(choices=[('Direct Debit', 'Direct Debit'), ('Regular', 'Regular')], max_length=20, null=True),
        ),
    ]
